=== mgm-tp/a12-uaa/uaa-authorization-language-server/src/internal/assets/schemas/authorization-definition-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"type": "object",
	"examples": [
		{
			"name": "",
			"description": "",
			"policies": [],
			"repositoryPolicies": [],
			"permissions": [],
			"propertyRights": [],
			"propertyPermissions": []
		}
	],
	"properties": {
		"name": {
			"type": "string",
			"minLength": 1
		},
		"description": {
			"type": "string"
		},
		"policies": {
			"description": "A list of policies that can be referenced from Permission and PropertyPermission.",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "file://policy-schema.json"
			}
		},
		"repositoryPolicies": {
			"description": "A list of repository polices that can be referenced from Permission.",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "file://repositoryPolicy-schema.json"
			}
		},
		"permissions": {
			"description": "A list of permissions that define what actions a user can perform.",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "file://permission-schema.json"
			}
		},
		"propertyRights": {
			"description": "A list of property rights that can be referenced from PropertyPermission.",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "file://propertyRight-schema.json"
			}
		},
		"propertyPermissions": {
			"description": "A list of property permissions that specify which properties a user can access and what actions they can perform.",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "file://propertyPermission-schema.json"
			}
		}
	},
	"required": ["name"],
	"additionalProperties": false,
	"allOf": [
		{
			"if": {
				"anyOf": [
					{
						"required": ["permissions"],
						"properties": {
							"permissions": {
								"contains": {
									"required": ["policy-refs"],
									"properties": {
										"policy-refs": {
											"minItems": 1
										}
									}
								}
							}
						}
					},
					{
						"required": ["propertyPermissions"],
						"properties": {
							"propertyPermissions": {
								"contains": {
									"required": ["policy-refs"],
									"properties": {
										"policy-refs": {
											"minItems": 1
										}
									}
								}
							}
						}
					}
				]
			},
			"then": {
				"required": ["policies"]
			}
		},
		{
			"if": {
				"anyOf": [
					{
						"required": ["permissions"],
						"properties": {
							"permissions": {
								"contains": {
									"required": ["repository-refs"],
									"properties": {
										"repository-refs": {
											"minItems": 1
										}
									}
								}
							}
						}
					},
					{
						"required": ["propertyPermissions"],
						"properties": {
							"propertyPermissions": {
								"contains": {
									"required": ["repository-refs"],
									"properties": {
										"repository-refs": {
											"minItems": 1
										}
									}
								}
							}
						}
					}
				]
			},
			"then": {
				"required": ["repositoryPolicies"]
			}
		},
		{
			"if": {
				"required": ["propertyPermissions"],
				"properties": {
					"propertyPermissions": {
						"contains": {
							"required": ["rights-refs"],
							"properties": {
								"rights-refs": {
									"minItems": 1
								}
							}
						}
					}
				}
			},
			"then": {
				"required": ["propertyRights"]
			}
		}
	]
}

=== mgm-tp/a12-uaa/uaa-authorization-language-server/test/authorizationDefinition.json
{
  "name": "Test Permission Definition",
  "description": "",
  "policies": [
    {
      "name": "Company reading rule",
      "description": "",
      "target": "print('Preload for:' + #resource)",
      "dataPreload": [
        "print('principal: ' + principal)"
      ],
      "rules": [
        "print('User login ' + principal.username)",
        "print('Resource: ' + #resource)",
        "principal.nationality == #resource.countryCode"
      ]
    },
    {
      "name": "Admin from Vietnam",
      "description": "All rules for admin user from Vietnam",
      "dataPreload": [
        "print('Generic: ' + hasNestedObjectWithPropertyValue(principal.authorities, 'accessRights', 'name', 'WRITE'))",
        "print('Concrete: ' + hasAccessRight('WRITE'))",
        "print('Has Role: ' + containsAnyRole({'Reviewer', 'none'}))"
      ],
      "rules": [
        "hasRole('Manager') && principal.nationality == 'VN'"
      ]
    },
    {
      "name": "User from Czech",
      "description": "Ordinary user from czech",
      "rules": [
        "hasRole('Reviewer') && principal.nationality == 'CZ'"
      ]
    },
    {
      "name": "Load All Companies Endpoint",
      "description": "",
      "rules": [
        "print('resource = ' +#resource)",
        "#resource == 'MainController.loadAllCompanies'"
      ]
    },
    {
      "name": "Save Company Endpoint",
      "description": "",
      "rules": [
        "#resource == 'MainController.saveCompany'"
      ]
    },
    {
      "name": "Update Company Endpoint",
      "description": "",
      "rules": [
        "#resource == 'MainController.updateCompany'"
      ]
    },
    {
      "name": "Load A12 Doc Endpoint",
      "description": "",
      "rules": [
        "#resource == 'MainController.loadProductDocuments'"
      ]
    },
    {
      "name": "Update A12 Doc Endpoint",
      "description": "",
      "rules": [
        "#resource == 'MainController.updateProductDocument'"
      ]
    },
    {
      "name": "A12 Product Admin",
      "description": "",
      "rules": [
        "#resource.documentModelId == 'product' ",
        "principal.nationality == #resource.product.countryCode"
      ]
    },
    {
      "name": "Company Domain Object",
      "description": "",
      "rules": [
        "#resource instanceof T(com.mgmtp.a12.uaa.example.entity.Company)"
      ]
    },
    {
      "name": "Product Document",
      "description": "",
      "rules": [
        "#resource instanceof T(com.mgmtp.a12.kernel.md.document.api.IDocument)",
        "#resource.documentModelId == 'Product'"
      ]
    }
  ],
  "repositoryPolicies": [
    {
      "name": "Repo Admin from Vietnam",
      "description": "All rules for admin user from Vietnam",
      "templates": [
        "'country_code = ' +  principal.nationality"
      ]
    }
  ],
  "permissions": [
    {
      "name": "Load Company",
      "description": "Demo",
      "policy-refs": [
        "Admin from Vietnam || User from Czech"
      ],
      "repository-refs": [
        "Repo Admin from Vietnam"
      ],
      "scopes": [
        "Load company"
      ]
    },
    {
      "name": "Update Company For Admin",
      "description": "",
      "policy-refs": [
        "Admin from Vietnam || User from Czech",
        "Update Company Endpoint"
      ],
      "scopes": [
        "Company update"
      ]
    },
    {
      "name": "Access External Company Admin",
      "description": "Example",
      "policies": [
        "print('loader context = ' + #companyDataLoaderContext)",
        "(#companyDataLoaderContext.userName == 'admin' && #companyDataLoaderContext.countryCode == 'VN') || (#companyDataLoaderContext.userName == 'tom' && #companyDataLoaderContext.countryCode == 'CZ')"
      ],
      "scopes": [
        "Access external company"
      ]
    },
    {
      "name": "Vietnam Company Manager Save",
      "description": "",
      "policy-refs": [
        "Admin from Vietnam || User from Czech",
        "Save Company Endpoint"
      ],
      "scopes": [
        "Company save"
      ]
    },
    {
      "name": "Access to A12 Doc",
      "description": "",
      "policy-refs": [
        "Load A12 Doc Endpoint || Update A12 Doc Endpoint"
      ],
      "scopes": [
        "A12 document"
      ]
    },
    {
      "name": "Access to A12 Doc For Admin",
      "description": "",
      "policy-refs": [
        "A12 Product Admin"
      ],
      "scopes": [
        "A12 document service"
      ]
    },
    {
      "name": "Actuator Permission",
      "description": "",
      "policies": [
        "print('Path Permission: ' + #resource)",
        "#resource.getRequestURI() == '/actuator/beans'"
      ],
      "policy-refs": [
        "Admin from Vietnam"
      ],
      "scopes": [
        "RelativePath"
      ]
    },
    {
      "name": "Reload Authorization Rules",
      "description": "",
      "policies": [
        "print('Path Permission: ' + #resource)",
        "print('Principal: ' + principal)"
      ],
      "policy-refs": [
        "Admin from Vietnam"
      ],
      "scopes": [
        "Reload Rules"
      ]
    },
    {
      "name": "Backend Task",
      "description": "",
      "policies": [
        "print('Backend Task: ' + #resource)",
        "print('Principal: ' + principal)",
        "#resource == 'BackendClass.backendTask'",
        "principal.username == 'exot'"
      ],
      "scopes": [
        "Backend Task"
      ]
    },
    {
      "name": "Upload Role Mapping Rules",
      "description": "",
      "policies": [
        "print('Path Permission: ' + #resource)",
        "print('Principal: ' + principal)"
      ],
      "policy-refs": [
        "Admin from Vietnam"
      ],
      "scopes": [
        "Upload Role Access Rights Mapping Rule"
      ]
    },
    {
      "name": "Anonymous",
      "description": "",
      "policies": [
        "print('Principal: ' + principal)",
        "principal.username == 'anonymous'",
        "containsAnyRole('ANONYMOUS')",
        "hasRole('ANONYMOUS')",
        "hasAccessRight('READ')"
      ],
      "scopes": [
        "Anonymous"
      ]
    },
    {
      "name": "uri-based authorization",
      "policies": [
        "true"
      ],
      "scopes": [
        "uri_based_ok_scope"
      ]
    }
  ],
  "propertyPermissions": [
    {
      "name": "Company Properties Admin",
      "description": "",
      "policy-refs": [
        "Company Domain Object",
        "Admin from Vietnam"
      ],
      "rights-refs": [
        "Company Entity For Admin"
      ]
    },
    {
      "name": "Company Czech",
      "description": "",
      "policy-refs": [
        "Company Domain Object || Company Domain Object",
        "Company Domain Object",
        "User from Czech"
      ],
      "rights-refs": [
        "Company Entity For Czech User"
      ]
    },
    {
      "name": "A12 Product Admin",
      "description": "",
      "policy-refs": [
        "Admin from Vietnam"
      ],
      "policies": [
        "#resource.documentModelId == 'product' ",
        "#resource.product.countryCode == 'VN' "
      ],
      "rights-refs": [
        "Product Document Admin"
      ]
    },
    {
      "name": "A12 Document For Czech User",
      "description": "",
      "policy-refs": [
        "User from Czech"
      ],
      "rights-refs": [
        "Company Entity For Admin",
        "Product Document For Czech User"
      ]
    }
  ],
  "propertyRights": [
    {
      "name": "Product Document Admin",
      "description": "",
      "rights": {
        "READ": [
          "id",
          "product.name",
          "product.countryCode",
          "product.mediaFiles[].mediaFile.mimeType",
          "product.mediaFiles[].mediaFile.url",
          "product.packaging.packagingUnit"
        ],
        "WRITE": [
          "product.name"
        ]
      }
    },
    {
      "name": "Product Document For Czech User",
      "description": "",
      "rights": {
        "READ": [
          "id",
          "product.name",
          "product.countryCode"
        ]
      }
    },
    {
      "name": "Company Entity For Czech User",
      "description": "",
      "rights": {
        "READ": [
          "id",
          "name",
          "countryCode",
          "taxNumber",
          "employees"
        ],
        "MASK": [
          "taxNumber::'masked: ' + taxNumber.substring(0,3) + '...'"
        ]
      }
    },
    {
      "name": "Company Entity For Admin",
      "description": "",
      "rights": {
        "READ": [
          "Root.Department.Title",
          "Root.Department.Description",
          "id",
          "name",
          "taxNumber"
        ],
        "WRITE": [
          "id",
          "name",
          "countryCode",
          "taxNumber",
          "employees",
          "employees[].id",
          "employees[].firstName",
          "employees[].lastName",
          "Root.Name",
          "Root.Description",
          "employees[].age"
        ]
      }
    }
  ]
}

=== mgm-tp/a12-uaa/uaa-authorization-a12-extension/src/test/resources/testModelAuthorizationDefinition.json
{
	"name": "Test Permission Definition",
	"description": "",
	"policies": [
		{
			"name": "SpEl_Policy",
			"description": "",
			"rules": [
				"#resource.resource.id != null",
				"#resource.resource.code != null",
				"#resource.resource.name != null",
				"#resource.resource.code == 'VN'",
				"#resource.principal.roles.size() > 0"
			]
		}
	],
	"permissions": [
		{
			"name": "Model permission SpEl",
			"description": "Inline Permissions",
			"policy-refs": [
				"SpEl_Policy"
			],
			"scopes": [
				"SpEl"
			]
		}
	]
}

=== mgm-tp/a12-uaa/uaa-authorization-a12-extension/src/test/resources/impfPortal/impfPortalAuthorizationDefinition_TK.json
{
  "name": "Impf Portal Authorization Definition",
  "description": "Example from Impf Portal",
  "policies": [
    {
      "name": "Admin_Guest_RegionManager",
      "description": "",
      "type": "A12Model",
      "dataPreload": [
        "#localName = 'local Name'",
        "#region = (hasRole('REGION_MANAGER') ? principal.region : '')",
        "#testValue = 'TEST'",
        "#username = (hasRole('REGION_MANAGER') || hasRole('GUEST') ? principal.username : '')"
      ],
      "rules": [
        "impfPortal/models/authorization/AuthorizationImpfPortal_TK.json"
      ]
    }
  ],
  "repositoryPolicies": [
    {
      "name": "Repository_Admin_Guest_RegionManager_Policy",
      "description": "Repos",
      "dataPreload": [
        "#username = (true ? 'nothing' : principal.username)",
        "#testValue = 'ABC'",
        "#region = (hasRole('REGION_MANAGER') ? principal.region : '')",
        "#username = (hasRole('REGION_MANAGER') || hasRole('GUEST') ? principal.username : '')"
      ],
      "templates": [
        "Admin_Guest_RegionManager"
      ]
    }
  ],
  "permissions": [
    {
      "name": "View all application",
      "description": "Users can view all applications with role 'ADMIN' or 'REGION_MANAGER' or 'GUEST' with specific rules.",
      "policy-refs": [
      ],
      "repository-refs" : [
        "Repository_Admin_Guest_RegionManager_Policy"
      ],
      "policies": [],
      "scopes": [
        "Document Read"
      ]
    }
  ]
}

=== mgm-tp/a12-uaa/uaa-authorization-a12-extension/src/test/resources/impfPortal/impfPortalAuthorizationDefinition.json
{
  "name": "Impf Portal Authorization Definition",
  "description": "Example from Impf Portal",
  "policies": [
    {
      "name": "Admin_Guest_RegionManager",
      "description": "",
      "type": "A12Model",
      "rules": [
        "impfPortal/models/authorization/AuthorizationImpfPortal_Full.json"
      ]
    }
  ],
  "repositoryPolicies": [
    {
      "name": "Repository_Admin_Guest_RegionManager_Policy",
      "description": "Repos",
      "templates": [
        "Admin_Guest_RegionManager"
      ]
    }
  ],
  "permissions": [
    {
      "name": "View all application",
      "description": "Users can view all applications with role 'ADMIN' or 'REGION_MANAGER' or 'GUEST' with specific rules.",
      "policy-refs": [
        "Admin_Guest_RegionManager"
      ],
      "repository-refs" : [
        "Repository_Admin_Guest_RegionManager_Policy"
      ],
      "scopes": [
        "View all application"
      ]
    }
  ]
}

=== mgm-tp/a12-uaa/uaa-authorization-a12-extension/src/test/resources/myCase/myCaseAuthorizationDefinition.json
{
  "name": "Domain Case Type Authorization Definition",
  "description": "Example Permission Definition for Domain Case Type",
  "policies": [
    {
      "name": "Domain Authorization Filter",
      "description": "",
      "dataPreload": [
        "#username = ((hasRole('admin') || #resource != 'DomainCaseType') ? '' : principal.username)",
        "print('Roles: ' + principal.authorities)",
        "print('UserName: ' + #username)",
        "print('Condition: ' + hasRole('admin') + ', Resource: ' +  #resource)" 
      ],
      "rules": [
        "myCase/models/authorization/DomainAuthorization_Full.json"
      ],
      "type": "A12Model"
    }
  ],
  "repositoryPolicies": [
    {
      "name": "Repository_Domain_Authorization_Filter_Policy_Ref",
      "description": "Repos",
      "dataPreload": [
        "#username = ((hasRole('admin') || #resource != 'DomainCaseType') ? '' : principal.username)"
      ],
      "templates": [
        "Domain Authorization Filter"
      ]
    }
  ],
  "permissions": [
    {
      "name": "Load Document",
      "description": "",
      "policy-refs": [
        "Domain Authorization Filter"
      ],
      "repository-refs": [
        "Repository_Domain_Authorization_Filter_Policy_Ref"
      ],
      "call-parent-scope": false,
      "scopes": [
        "Document Read"
      ]
    }
  ]
}
